// Auto-generated by `pnpm gen:types`. Do not edit by hand.
// Source: Supabase project (configurado em runtime via ConfigGate)

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: { PostgrestVersion: "14.5" }
  public: {
    Tables: {
      audit_log: {
        Row: {
          acao: Database["public"]["Enums"]["acao_audit"]
          entidade: string
          entidade_id: string
          id: number
          ip: string | null
          motivo: string | null
          ts: string
          user_agent: string | null
          usuario_id: string
          valores_antes: Json | null
          valores_depois: Json | null
        }
        Insert: {
          acao: Database["public"]["Enums"]["acao_audit"]
          entidade: string
          entidade_id: string
          id?: number
          ip?: string | null
          motivo?: string | null
          ts?: string
          user_agent?: string | null
          usuario_id: string
          valores_antes?: Json | null
          valores_depois?: Json | null
        }
        Update: {
          acao?: Database["public"]["Enums"]["acao_audit"]
          entidade?: string
          entidade_id?: string
          id?: number
          ip?: string | null
          motivo?: string | null
          ts?: string
          user_agent?: string | null
          usuario_id?: string
          valores_antes?: Json | null
          valores_depois?: Json | null
        }
        Relationships: []
      }
      centros_de_custo: {
        Row: {
          ativo: boolean
          codigo: string
          created_at: string
          id: string
          nome: string
        }
        Insert: {
          ativo?: boolean
          codigo: string
          created_at?: string
          id?: string
          nome: string
        }
        Update: {
          ativo?: boolean
          codigo?: string
          created_at?: string
          id?: string
          nome?: string
        }
        Relationships: []
      }
      chat_messages: {
        Row: {
          body: string
          created_at: string
          id: string
          read_at: string | null
          recipient_id: string
          sender_id: string
        }
        Insert: {
          body: string
          created_at?: string
          id?: string
          read_at?: string | null
          recipient_id: string
          sender_id: string
        }
        Update: {
          body?: string
          created_at?: string
          id?: string
          read_at?: string | null
          recipient_id?: string
          sender_id?: string
        }
        Relationships: []
      }
      contas_bancarias: {
        Row: {
          agencia: string | null
          apelido: string
          ativo: boolean
          banco: string
          created_at: string
          empresa_id: string
          id: string
          numero: string | null
          tipo: Database["public"]["Enums"]["conta_tipo"]
        }
        Insert: {
          agencia?: string | null
          apelido: string
          ativo?: boolean
          banco: string
          created_at?: string
          empresa_id: string
          id?: string
          numero?: string | null
          tipo: Database["public"]["Enums"]["conta_tipo"]
        }
        Update: {
          agencia?: string | null
          apelido?: string
          ativo?: boolean
          banco?: string
          created_at?: string
          empresa_id?: string
          id?: string
          numero?: string | null
          tipo?: Database["public"]["Enums"]["conta_tipo"]
        }
        Relationships: []
      }
      empresas: {
        Row: {
          ativo: boolean
          cnpj: string | null
          created_at: string
          id: string
          nome_fantasia: string | null
          razao_social: string
          updated_at: string
        }
        Insert: {
          ativo?: boolean
          cnpj?: string | null
          created_at?: string
          id?: string
          nome_fantasia?: string | null
          razao_social: string
          updated_at?: string
        }
        Update: {
          ativo?: boolean
          cnpj?: string | null
          created_at?: string
          id?: string
          nome_fantasia?: string | null
          razao_social?: string
          updated_at?: string
        }
        Relationships: []
      }
      fornecedores_clientes: {
        Row: {
          ativo: boolean
          created_at: string
          documento: string | null
          id: string
          nome: string
          tipo: Database["public"]["Enums"]["pessoa_tipo"]
        }
        Insert: {
          ativo?: boolean
          created_at?: string
          documento?: string | null
          id?: string
          nome: string
          tipo: Database["public"]["Enums"]["pessoa_tipo"]
        }
        Update: {
          ativo?: boolean
          created_at?: string
          documento?: string | null
          id?: string
          nome?: string
          tipo?: Database["public"]["Enums"]["pessoa_tipo"]
        }
        Relationships: []
      }
      lancamentos: {
        Row: {
          centro_custo_id: string
          conciliacao_observacao: string | null
          conciliado_em: string | null
          conciliado_por: string | null
          conta_destino_id: string | null
          conta_origem_id: string | null
          created_at: string
          data: string
          descricao: string
          estorno_de_id: string | null
          fornecedor_cliente_id: string | null
          fornecedor_cliente_texto: string | null
          id: string
          motivo_estorno: string | null
          natureza: Database["public"]["Enums"]["natureza_lancamento"]
          observacoes: string | null
          responsavel_id: string
          ri: string | null
          tipo_operacao_id: string
          updated_at: string
          valor: number
        }
        Insert: {
          centro_custo_id: string
          conciliacao_observacao?: string | null
          conciliado_em?: string | null
          conciliado_por?: string | null
          conta_destino_id?: string | null
          conta_origem_id?: string | null
          created_at?: string
          data: string
          descricao: string
          estorno_de_id?: string | null
          fornecedor_cliente_id?: string | null
          fornecedor_cliente_texto?: string | null
          id?: string
          motivo_estorno?: string | null
          natureza: Database["public"]["Enums"]["natureza_lancamento"]
          observacoes?: string | null
          responsavel_id: string
          ri?: string | null
          tipo_operacao_id: string
          updated_at?: string
          valor: number
        }
        Update: {
          centro_custo_id?: string
          conciliacao_observacao?: string | null
          conciliado_em?: string | null
          conciliado_por?: string | null
          conta_destino_id?: string | null
          conta_origem_id?: string | null
          created_at?: string
          data?: string
          descricao?: string
          estorno_de_id?: string | null
          fornecedor_cliente_id?: string | null
          fornecedor_cliente_texto?: string | null
          id?: string
          motivo_estorno?: string | null
          natureza?: Database["public"]["Enums"]["natureza_lancamento"]
          observacoes?: string | null
          responsavel_id?: string
          ri?: string | null
          tipo_operacao_id?: string
          updated_at?: string
          valor?: number
        }
        Relationships: []
      }
      periodos_fechados: {
        Row: {
          fechado_em: string
          fechado_por: string
          id: string
          motivo_reabertura: string | null
          periodo: string
          reaberto_em: string | null
          reaberto_por: string | null
          totals_hash: string | null
        }
        Insert: {
          fechado_em?: string
          fechado_por: string
          id?: string
          motivo_reabertura?: string | null
          periodo: string
          reaberto_em?: string | null
          reaberto_por?: string | null
          totals_hash?: string | null
        }
        Update: {
          fechado_em?: string
          fechado_por?: string
          id?: string
          motivo_reabertura?: string | null
          periodo?: string
          reaberto_em?: string | null
          reaberto_por?: string | null
          totals_hash?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          ativo: boolean
          created_at: string
          email: string
          id: string
          is_magnata: boolean
          is_superadmin: boolean
          nome_completo: string
          role: Database["public"]["Enums"]["user_role"]
          updated_at: string
        }
        Insert: {
          ativo?: boolean
          created_at?: string
          email: string
          id: string
          is_magnata?: boolean
          is_superadmin?: boolean
          nome_completo: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Update: {
          ativo?: boolean
          created_at?: string
          email?: string
          id?: string
          is_magnata?: boolean
          is_superadmin?: boolean
          nome_completo?: string
          role?: Database["public"]["Enums"]["user_role"]
          updated_at?: string
        }
        Relationships: []
      }
      saldos_iniciais: {
        Row: {
          conta_id: string
          created_at: string
          created_by: string | null
          id: string
          periodo: string
          valor: number
        }
        Insert: {
          conta_id: string
          created_at?: string
          created_by?: string | null
          id?: string
          periodo: string
          valor: number
        }
        Update: {
          conta_id?: string
          created_at?: string
          created_by?: string | null
          id?: string
          periodo?: string
          valor?: number
        }
        Relationships: []
      }
      solicitacoes_saldo: {
        Row: {
          centro_custo_id: string | null
          conta_destino_id: string
          conta_origem_efetiva_id: string | null
          conta_origem_sugerida_id: string | null
          created_at: string
          descricao: string
          id: string
          lancamento_gerado_id: string | null
          motivo_rejeicao: string | null
          observacao_aprovacao: string | null
          resolvida_em: string | null
          resolvida_por: string | null
          solicitante_id: string
          status: Database["public"]["Enums"]["status_solicitacao"]
          updated_at: string
          valor: number
        }
        Insert: {
          centro_custo_id?: string | null
          conta_destino_id: string
          conta_origem_efetiva_id?: string | null
          conta_origem_sugerida_id?: string | null
          created_at?: string
          descricao: string
          id?: string
          lancamento_gerado_id?: string | null
          motivo_rejeicao?: string | null
          observacao_aprovacao?: string | null
          resolvida_em?: string | null
          resolvida_por?: string | null
          solicitante_id: string
          status?: Database["public"]["Enums"]["status_solicitacao"]
          updated_at?: string
          valor: number
        }
        Update: {
          centro_custo_id?: string | null
          conta_destino_id?: string
          conta_origem_efetiva_id?: string | null
          conta_origem_sugerida_id?: string | null
          created_at?: string
          descricao?: string
          id?: string
          lancamento_gerado_id?: string | null
          motivo_rejeicao?: string | null
          observacao_aprovacao?: string | null
          resolvida_em?: string | null
          resolvida_por?: string | null
          solicitante_id?: string
          status?: Database["public"]["Enums"]["status_solicitacao"]
          updated_at?: string
          valor?: number
        }
        Relationships: []
      }
      tipos_operacao: {
        Row: {
          ativo: boolean
          codigo: string
          created_at: string
          id: string
          is_transferencia: boolean
          nome: string
        }
        Insert: {
          ativo?: boolean
          codigo: string
          created_at?: string
          id?: string
          is_transferencia?: boolean
          nome: string
        }
        Update: {
          ativo?: boolean
          codigo?: string
          created_at?: string
          id?: string
          is_transferencia?: boolean
          nome?: string
        }
        Relationships: []
      }
      user_contas_permitidas: {
        Row: {
          conta_id: string
          granted_at: string
          granted_by: string | null
          pode_lancar: boolean
          pode_ver: boolean
          user_id: string
        }
        Insert: {
          conta_id: string
          granted_at?: string
          granted_by?: string | null
          pode_lancar?: boolean
          pode_ver?: boolean
          user_id: string
        }
        Update: {
          conta_id?: string
          granted_at?: string
          granted_by?: string | null
          pode_lancar?: boolean
          pode_ver?: boolean
          user_id?: string
        }
        Relationships: []
      }
      user_modulos: {
        Row: {
          granted_at: string
          granted_by: string | null
          modulo: Database["public"]["Enums"]["modulo_app"]
          user_id: string
        }
        Insert: {
          granted_at?: string
          granted_by?: string | null
          modulo: Database["public"]["Enums"]["modulo_app"]
          user_id: string
        }
        Update: {
          granted_at?: string
          granted_by?: string | null
          modulo?: Database["public"]["Enums"]["modulo_app"]
          user_id?: string
        }
        Relationships: []
      }
    }
    Views: {
      v_chat_contatos: {
        Row: {
          id: string | null
          is_magnata: boolean | null
          is_superadmin: boolean | null
          nome_completo: string | null
          role: string | null
        }
        Relationships: []
      }
      v_chat_conversas: {
        Row: {
          nao_lidas: number | null
          ultima_msg: string | null
          ultima_msg_em: string | null
          ultima_sender_id: string | null
          user_a: string | null
          user_a_nome: string | null
          user_a_role: string | null
          user_b: string | null
          user_b_nome: string | null
          user_b_role: string | null
        }
        Relationships: []
      }
      v_conferencia: {
        Row: {
          contas_divergentes: number | null
          periodo: string | null
          saldo_calculado: number | null
          status: string | null
          total_entradas: number | null
          total_saidas: number | null
          total_saldo_atual: number | null
          total_saldo_inicial: number | null
          total_transferencias_enviadas: number | null
          total_transferencias_recebidas: number | null
        }
        Relationships: []
      }
      v_contas_lookup: {
        Row: {
          id: string | null
          apelido: string | null
        }
        Relationships: []
      }
      v_contas_saldo: {
        Row: {
          apelido: string | null
          ativo: boolean | null
          banco: string | null
          conta_id: string | null
          empresa: string | null
          empresa_id: string | null
          numero: string | null
          saldo_atual: number | null
          tipo: Database["public"]["Enums"]["conta_tipo"] | null
        }
        Relationships: []
      }
      v_dashboard_centro_custo: {
        Row: {
          centro_custo: string | null
          centro_custo_id: string | null
          codigo: string | null
          entradas: number | null
          periodo: string | null
          qtd_lancamentos: number | null
          saidas: number | null
          saldo_liquido: number | null
        }
        Relationships: []
      }
      v_entradas_saidas_usuario: {
        Row: {
          conta_apelido: string | null
          conta_id: string | null
          entrada: number | null
          periodo: string | null
          responsavel_id: string | null
          responsavel_nome: string | null
          saida: number | null
        }
        Relationships: []
      }
      v_fluxo_diario: {
        Row: {
          data: string | null
          entradas: number | null
          saidas: number | null
        }
        Relationships: []
      }
      v_fluxo_mensal: {
        Row: {
          entradas: number | null
          liquido: number | null
          periodo: string | null
          qtd_lancamentos: number | null
          saidas: number | null
        }
        Relationships: []
      }
      v_movimentos: {
        Row: {
          centro_custo_id: string | null
          conta_id: string | null
          data: string | null
          direcao: string | null
          efeito: number | null
          is_transferencia: boolean | null
          lancamento_id: string | null
          periodo: string | null
          responsavel_id: string | null
          tipo_operacao_id: string | null
        }
        Relationships: []
      }
      v_pendentes_conciliacao: {
        Row: {
          conta_apelido: string | null
          conta_destino_id: string | null
          conta_origem_id: string | null
          data: string | null
          descricao: string | null
          id: string | null
          natureza: Database["public"]["Enums"]["natureza_lancamento"] | null
          responsavel_id: string | null
          responsavel_nome: string | null
          valor: number | null
        }
        Relationships: []
      }
      v_saldo_geral: {
        Row: {
          conta: string | null
          conta_id: string | null
          conta_tipo: Database["public"]["Enums"]["conta_tipo"] | null
          empresa: string | null
          empresa_id: string | null
          entradas: number | null
          periodo: string | null
          periodo_fechado: boolean | null
          saidas: number | null
          saldo_atual: number | null
          saldo_inicial: number | null
          status: string | null
          transferencias_enviadas: number | null
          transferencias_recebidas: number | null
        }
        Relationships: []
      }
      v_saldo_por_conta_usuario: {
        Row: {
          conta_apelido: string | null
          conta_id: string | null
          empresa: string | null
          empresa_id: string | null
          entradas: number | null
          periodo: string | null
          responsavel_id: string | null
          responsavel_nome: string | null
          saidas: number | null
          saldo_liquido: number | null
        }
        Relationships: []
      }
      v_saldo_por_empresa: {
        Row: {
          empresa_id: string | null
          nome_fantasia: string | null
          qtd_contas: number | null
          razao_social: string | null
          saldo_total: number | null
        }
        Relationships: []
      }
      v_top_fornecedores: {
        Row: {
          documento: string | null
          fornecedor_id: string | null
          nome: string | null
          pessoa_tipo: Database["public"]["Enums"]["pessoa_tipo"] | null
          qtd_lancamentos: number | null
          total_saidas: number | null
          ultima_movimentacao: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      apagar_dados_teste: {
        Args: never
        Returns: {
          audit_log_removidos: number
          lancamentos_removidos: number
          periodos_removidos: number
          saldos_iniciais_removidos: number
          solicitacoes_removidas: number
        }[]
      }
      aprovar_solicitacao_saldo: {
        Args: {
          p_centro_custo_id?: string
          p_conta_origem_id: string
          p_observacao?: string
          p_solic_id: string
        }
        Returns: string
      }
      chat_marcar_lidas: { Args: { p_sender_id: string }; Returns: number }
      chat_nao_lidas_total: { Args: never; Returns: number }
      chat_listar_contatos: {
        Args: never
        Returns: {
          id: string
          nome_completo: string
          role: string
          is_superadmin: boolean
          is_magnata: boolean
        }[]
      }
      chat_contato_por_id: {
        Args: { p_id: string }
        Returns: {
          id: string
          nome_completo: string
          role: string
          is_superadmin: boolean
          is_magnata: boolean
        }[]
      }
      grant_default_modulos: {
        Args: { p_grantor?: string; p_user_id: string }
        Returns: undefined
      }
      is_admin_financeiro: { Args: never; Returns: boolean }
      is_superadmin: { Args: never; Returns: boolean }
      is_usuario_ativo: { Args: never; Returns: boolean }
      magnata_alertas: { Args: never; Returns: Json }
      magnata_kpis: { Args: never; Returns: Json }
      magnata_projecao_caixa: {
        Args: { p_dias?: number }
        Returns: {
          banda_inferior: number
          banda_superior: number
          data: string
          saldo_projetado: number
        }[]
      }
      meus_modulos: {
        Args: never
        Returns: { modulo: Database["public"]["Enums"]["modulo_app"] }[]
      }
      periodo_esta_fechado: { Args: { p_data: string }; Returns: boolean }
      pode_lancar_conta: { Args: { p_conta_id: string }; Returns: boolean }
      pode_ver_conta: { Args: { p_conta_id: string }; Returns: boolean }
      pode_ver_modulo: {
        Args: { p_modulo: Database["public"]["Enums"]["modulo_app"] }
        Returns: boolean
      }
      rejeitar_solicitacao_saldo: {
        Args: { p_motivo: string; p_solic_id: string }
        Returns: undefined
      }
      saldo_atual_conta: { Args: { p_conta_id: string }; Returns: number }
    }
    Enums: {
      acao_audit:
        | "CREATE"
        | "UPDATE"
        | "DELETE"
        | "LOCK"
        | "UNLOCK"
        | "APPROVE"
        | "REJECT"
        | "OVERRIDE"
      conta_tipo:
        | "CORRENTE"
        | "POUPANCA"
        | "CAIXA_FISICO"
        | "CARTAO_CREDITO_CONTA"
      modulo_app:
        | "dashboard"
        | "saldo_geral"
        | "centros_de_custo"
        | "conferencia"
        | "conciliacao"
        | "lancamentos"
        | "fornecedores"
        | "solicitacoes"
        | "solicitacoes_aprovar"
        | "auditoria"
        | "periodos"
        | "saldos_iniciais"
        | "permissoes"
        | "empresas"
        | "contas"
        | "centros_admin"
        | "tipos_operacao"
        | "magnata_dashboard"
      natureza_lancamento: "ENTRADA" | "SAIDA"
      pessoa_tipo: "PF" | "PJ"
      status_solicitacao: "PENDENTE" | "APROVADA" | "REJEITADA" | "CANCELADA"
      user_role: "admin_financeiro" | "usuario_financeiro"
    }
    CompositeTypes: { [_ in never]: never }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never
