-- FORNECEDORES (upsert por nome, normaliza maiúsculas)
-- Tipo padrão PJ; ajuste manual depois pra PF se necessário.
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Aibara', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Antonio Cleiciano', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Artidorio Poncio', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('BANCO DO BRASIL', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('CAIXA FISICO', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Caixa Fisico', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Casa dos parafusos', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Conta Simples', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Cruz e santos', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Damião', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Farmacia MB', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Fortebras', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Fortelona', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Franciane Fonte', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Fumaça', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Giro', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Hidrauron', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('ICCAP implementos', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('J & c serviço mecanico', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('JOEL VERISSIMO DA ROCHA', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Jenario Lucas', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Lineagro', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Lionardo dos santos', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Lucimar de souza', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('MI TRR Transportadora', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Maikon', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Mercado cristal', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Moreno e Martinhago', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Natalia', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Noma Truck', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Olifer comercio de aço', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Pedagio nova 364', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Ponto certo', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Posto Falcon', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Posto Mirian', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Posto Puma', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Posto Uniao', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Posto União', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Posto doralice', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('RODOAGRO SANTANDER', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('RODOAGRO SICREDI', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('RODOPAV CONSTRUTORA', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('RODOPAV TRANSPORTE', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('RODOPAV TRANSPORTE OPERACIONAL', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Road Asfaltos', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Road Concretos', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Road asfaltos', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Rodobens', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Rodopav Construtora', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Rodopav Transportes', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Rodopav transportes', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Ronaldo Teles', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Transpib Transportadora', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Violato Recapadora', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('Yuri', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('bb boletos', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('bb despesas', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('bb manutenção', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('bb rtc', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('pagamento a fornecedor', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('pro labore ze', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('recebimento avulso', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('rescisao rtc washigton tawan', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('road concretos', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('rodopav transportes', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('santander rodopav', 'PJ') ON CONFLICT DO NOTHING;
INSERT INTO fornecedores_clientes (nome, tipo) VALUES ('transportes operacional', 'PJ') ON CONFLICT DO NOTHING;